# Generated by Django 2.2.3 on 2019-07-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complaindate',
            field=models.CharField(default='Test', max_length=30),
            preserve_default=False,
        ),
    ]
