# Generated by Django 2.2.3 on 2019-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalzone', '0002_customerinfo_logininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='contactno',
            field=models.CharField(default='Test', max_length=15),
            preserve_default=False,
        ),
    ]
